config:
  update-conf-2024:azure-resource-group-name: dev-feedback-rg
  update-conf-2024:functions-package-path: local
  update-conf-2024:location: eastus2
  update-conf-2024:static-site-path: local
  update-conf-2024:service-config: 
    Version: local
    Environment: dev
  update-conf-2024:resource-users-config:
    GroupName: dev-users
    Users:
    - AL@programmeral.com
pulumi:template: azure-csharp
