name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      DOTNET_VERSION: 8.x.x
      SRC_DIRECTORY_PATH: ${{ github.workspace }}/update-conference-prague-2024/demo-code-feedback-system
      BUILD_ARTIFACTS_PATH: ${{ github.workspace }}/build_artifacts

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.3.0

        # Install Aspire workload - We don't use it for anything when deployed, but the Aspire Dashboard does get compiled by the Cake app. Install the workload just to make our lives a little easier.
      - name: Install .NET WASM Tools Workload
        run: dotnet workload install wasm-tools
      - name: Install .NET Aspire Workload
        run: dotnet workload install aspire

      - name: Cake Frosting Build
        run: dotnet run --project ${{ env.SRC_DIRECTORY_PATH }}/build/build/Build.csproj -- --BuildConfiguration=${{ env.CONFIGURATION }} --srcDirectoryPath=${{ github.SRC_DIRECTORY_PATH }} --BuildArtifactsPath=${{ github.run_id }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ${{ env.BUILD_ARTIFACTS_PATH }}

